def convert_to_camel_case(novel_name):
    # Define a mapping of uppercase words to camel case
    mapping = {
        'ARRONTROW': 'Arron Trow',
        'DOCTORTHORNE': 'Doctor Thorne',
        'HOUSEOFHEINEBROTHERSINMUNICH': 'House Of Heine Brothers In Munich',
        'GEORGEWALKERATSUEZ': 'George Walker At Suez',
        'THEMANWHOKEPTHISMONEYINABOX': 'The Man Who Kept His Money In A Box',
        'THECHURCHOFENGLAND': 'The Church Of England',
        'SIRHARRYHOTSPUROFHUMBLETHWAITE': 'Sir Harry Hotspur Of Humblethwaite',
        'ARIDEACROSSPALESTINE': 'A Ride Across Palestine',
        'LINDATRESSEL': 'Linda Tressel',
        'ORLEYFARM': 'Orley Farm',
        'BARCHESTERTOWERS': 'Barchester Towers',
        'CASTLERICHMOND': 'Castle Richmond',
        'FRAMLEYPARSONAGE': 'Framley Parsonage',
        'LORDPALMERSTON': 'Lord Palmerston',
        'STRUGGLESOFBROWNJONESANDROBINSON': 'Struggles Of Brown Jones And Robinson',
        'THELASTCHRONICLEOFBARSET': 'The Last Chronicle Of Barset',
        'THELANDLEAGUERS': 'The Land Leaguers',
        'WHYFRAUFROHMANNRAISEDHERPRICES': 'Why Frau Frohmann Raised Her Prices',
        'ANUNPROTECTEDFEMALEATTHEPYRAMIDS': 'An Unprotected Female At The Pyramids',
        'THEMISTLETOEBOUGH': 'The Mistletoe Bough',
        'HARRYHEATHCOTEOFGANGOIL': 'Harry Heathcote Of Gangoil',
        'HUNTINGSKETCHES': 'Hunting Sketches',
        'THECLAVERINGS': 'The Claverings',
        'PHINEASFINN': 'Phineas Finn',
        'TALESOFALLCOUNTRIES': 'Tales Of All Countries',
        'JOHNCALDIGATE': 'John Caldigate',
        'THEBELTONESTATE': 'The Belton Estate',
        'KEPTINTHEDARK': 'Kept In The Dark',
        'LAMEREBAUCHE': 'La Mere Bauche',
        'AARONTROW': 'Aaron Trow',
        'LOTTASCHMIDTandOTHERSTORIES': 'Lotta Schmidt And Other Stories',
        'JOHNBULLONTHEGUADALQUIVIR': 'John Bull On The Guadalquivir',
        'THEWAYWELIVENOW': 'The Way We Live Now',
        'COUSINHENRY': 'Cousin Henry',
        'THEEUSTACEDIAMONDS': 'The Eustace Diamonds',
        'THETHREECLERKS': 'The Three Clerks',
        'THEAMERICANSENATOR': 'The American Senator',
        'LADYANNA': 'Lady Anna',
        'THEWARDEN': 'The Warden',
        'THESMALLHOUSEATALLINGTON': 'The Small House At Allington',
        'ANEYEFORANEYE': 'An Eye For An Eye',
        'RALPHTHEHEIR': 'Ralph The Heir',
        'MARIONFAY': 'Marion Fay',
        'HEKNEWHEWASRIGHT': 'He Knew He Was Right',
        'TRAVELLINGSKETCHES': 'Travelling Sketches',
        'CHRISTMASATTHOMPSONHAL': 'Christmas At Thompson Hal',
        'LAVENDEE': 'La Vendee',
        'MISSMACKENZIE': 'Miss Mackenzie',
        'CANYOUFORGIVEHER': 'Can You Forgive Her',
        'THECHATEAUOFPRINCEPOLIGNAC': 'The Chateau Of Prince Polignac',
        'RETURNINGHOME': 'Returning Home',
        'THECOURTSHIPOFSUSANBELL': 'The Courtship Of Susan Bell',
        'MISSSARAHJACKOFSPANISHTOWN': 'Miss Sarah Jack Of Spanish Town',
        'RACHELRAY': 'Rachel Ray',
        'THEPRIMEMINISTER': 'The Prime Minister',
        'NINABALATKA': 'Nina Balatka',
        'THEFIXEDPERIOD': 'The Fixed Period',
        'THEGOLDENLIONOFGRANPERE': 'The Golden Lion Of Granpere',
        'PHINEASREDUX': 'Phineas Redux',
        'THEMACDERMOTSOFBALLYCLORAN': 'The Macdermots Of Ballycloran',
        'THEVICAROFBULLHAMPTON': 'The Vicar Of Bullhampton',
        'THACKERAY': 'Thackeray',
        'THEBERTRAMS': 'The Bertrams',
    }
    # Return the camel case version of the novel name, if it exists in the mapping
    return mapping.get(novel_name, novel_name)





